version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'daily'
    commit_message:
      prefix: 'dependencies'
    allowed_updates:
      - match:
          update_type: 'security'
