language: node_js
services:
  - mongodb
node_js:
  - 6
script:
  - npm test
  - npm run coveralls
deploy:
  provider: npm
  email: "szokodiakos@gmail.com"
  api_key:
    secure: "mhOKFZJJPPsVLIbTCi0tOxcBdVDjjjBt0dGe0a4LKgdjQjI1cbtra/qHlu+6V85GRBJPOXfuaLXgg8wrPFYuHWIgnBCV0MI6Xwbq+4q0O4JiLEP2djhxjIZuavA1QA4eGNebpIS/SZl1m1OUk6pRjc5rntxWHVuX6EHR7ZCrm0OYMcA/oHtrbInk+fZDCL1kpSKp3+hHxN1HxcRdHn06OfrMIKauXxHa5BhbH0HLHIuKK1xtVIjj2Je0k1bNDF7VR0lcrS2RFJbn5BeMJ+qLvyi2RgRgfYF5DwRwmk/9KmgGNs8OTIzm2onKVg9Xkp6vfu4yf9Rsac4BjJzsCsC0NKk9lTBINB+p8sQWstuD5uKM84q2ZbxAsikHfohVDFPnRLwpIkSJJrF02fK5ickPvi8u/+vnNcNl55js7TCcG4MLXyytbYyUOrNXCT24Qy3EKAVABjP38zL++IxkkcMbb0x1vO1+lNZrPdr6WRCw8vGTqrhcmZtYDrJagrKTdcHEeTINSYW4cTOPrNoQPCS1SdnML9WitnlnYM3c2DeE3OQMxxc5LeOImIY3ElGccfWILJFhv8hKoUhLeKE5e6/qJLe+4mBgN1yHiRs5bflY6Clwp/J0lwnloGaX7W2TB+JKbXnwSPKII12Z5unuAvLiRU0+wdedJoLsRyDh5j/93l4="
  on:
    branch: master
