language: node_js
services:
  - mongodb
node_js:
  - 6
script:
  - npm test
  - npm run coveralls
deploy:
  provider: npm
  email: "szokodiakos@gmail.com"
  api_key:
    secure: "N/HLbKkbEKPIISgHjjEi1gtBbexAwMWslXqkK1qnQSUDRtwwnIAc3xYZFhfRy0jThkKt8Jf3ATgt+luMcoR/LMDrAUXoATGuqn0unqC7bJKDvMeMTpliFCL+05XYv/TJmN+B4dqmTnzRun/f96ZPghbokm4MfCNYjGeY6jvE1ffdiu7NAnT4fXCfAcuH5rTkhdEZegJ89wKKUwHjX7mpg/Ofi/h36am4vlxOXZ25ErwQAX2XpaBgExWvUvbOFMZfHASOdSCa3WRwB0CvFdHRienfiWjNW85efao99xU2BPYpc2pq1MaebLKbWG7hB+OPuchG3XgP9XhYaMbGh/GGV1kstBwJqxSR4aT3OUAR4bDflwYz9kPDbDAKmco1oqA9GTXlKbtzHBpl0U9fWQz5EsHvDh1PcFu0GA4lXx7n6iO2RWnNsJepL5DvH1PyyDRMPov2bqk7ByjCmJEz+cxI/Js/hGch1SSjvX2r3XB7RCbvnWa72NeP1UlzN0bD7ZUjf86qTBuyhq8ohhREdalXS+oRq2neEhO5CMsjm74xbX0KRFfZe2q9Bi2hdycNAuVptDDHvpVTP2F20SWpkiQs5ToHQQiBKphY90SGbVtWJsvWBzAlueYCIguwgNHdmFicejAIGvZcE9hBo6Yoc2C3NOZJABsa+yeKkQw9MgcHaAg="
  on:
    branch: master
